// sample dataset. use to test frontend components if backend is not working. 

const cars = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    variant: "Altis Grande 1.8 CVT",
    year: 2022,
    price: 5800000,
    city: "Lahore",
    mileage: 35000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Silver",
    bodyType: "Sedan",
    engineCapacity: "1800cc",
    description: "Single owner, genuine mileage, original paint throughout. All documents clear. No accident history. Available for inspection anytime.",
    image: "https://i0.wp.com/www.toyotaravi.com/wp-content/uploads/2015/12/exterior-main-1.jpg?fit=1265%2C600&ssl=1"
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    variant: "Oriel 1.8 i-VTEC CVT",
    year: 2021,
    price: 6200000,
    city: "Karachi",
    mileage: 42000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Grey Graphite",
    bodyType: "Sedan",
    engineCapacity: "1800cc",
    description: "Honda Atlas maintained. All genuine parts. Excellent condition. Serious buyers only.",
    image: "https://autos.hamariweb.com/images/carimages/4800_1.jpg"
  },
  {
    id: 3,
    make: "Suzuki",
    model: "Alto",
    variant: "VXR AGS",
    year: 2023,
    price: 2100000,
    city: "Islamabad",
    mileage: 12000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Cyan",
    bodyType: "Hatchback",
    engineCapacity: "660cc",
    description: "Like new condition. Perfect for city commuting. Excellent fuel economy. No work needed.",
    image: "https://tyrepoint.pk/wp-content/uploads/2019/09/Suzuki-Alto_2019-5.jpg"
  },
  {
    id: 4,
    make: "Kia",
    model: "Sportage",
    variant: "FWD Alpha AT",
    year: 2022,
    price: 8500000,
    city: "Lahore",
    mileage: 28000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Deep Blue",
    bodyType: "SUV",
    engineCapacity: "2000cc",
    description: "Sunroof, leather seats, all features working. Family used vehicle. Price is negotiable.",
    image: "https://kiamotors-portqasim.com/wp-content/uploads/2020/07/Kia-Sportage-Alpha.jpg"
  },
  {
    id: 5,
    make: "Toyota",
    model: "Yaris",
    variant: "ATIV X CVT",
    year: 2023,
    price: 3800000,
    city: "Faisalabad",
    mileage: 18000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Attitude Black",
    bodyType: "Sedan",
    engineCapacity: "1500cc",
    description: "Push start, alloy rims, reverse camera. No work needed. Excellent daily driver.",
    image: "https://www.toyota-central.com/Assets/images/Vehicle/Yaris/Color/attitude-black.png"
  },
  {
    id: 6,
    make: "Honda",
    model: "City",
    variant: "Aspire 1.5 CVT",
    year: 2022,
    price: 4100000,
    city: "Rawalpindi",
    mileage: 31000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "White",
    bodyType: "Sedan",
    engineCapacity: "1500cc",
    description: "Honda Atlas maintained. Sunroof variant. All original. Price slightly negotiable.",
    image: "https://i.ytimg.com/vi/HLjb8jgZsh8/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAdSJcWEuPjgi1WdX_329RIBOrufg"
  },
  {
    id: 7,
    make: "Toyota",
    model: "Fortuner",
    variant: "Sigma 4 2.7 AT",
    year: 2021,
    price: 14500000,
    city: "Karachi",
    mileage: 55000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Silver Metallic",
    bodyType: "SUV",
    engineCapacity: "2700cc",
    description: "4x4 variant. Excellent condition. All features working. Documentation complete. No leaks.",
    image: "https://www.toyota-central.com/Assets/images/Vehicle/Fortuner/Fortunier.png"
  },
  {
    id: 8,
    make: "Suzuki",
    model: "Swift",
    variant: "GLX CVT",
    year: 2022,
    price: 3200000,
    city: "Multan",
    mileage: 22000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Grey Graphite",
    bodyType: "Hatchback",
    engineCapacity: "1200cc",
    description: "Sporty and fuel efficient. Perfect daily driver. Single owner. Genuine mileage.",
    image: "https://autos.hamariweb.com/images/carimages/car_0197_594940.jpg"
  },
  {
    id: 9,
    make: "Hyundai",
    model: "Tucson",
    variant: "GLS Sport FWD AT",
    year: 2022,
    price: 9200000,
    city: "Islamabad",
    mileage: 33000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Sky Blue",
    bodyType: "SUV",
    engineCapacity: "2000cc",
    description: "Panoramic sunroof, ventilated seats, all features intact. Immaculate condition.",
    image: "https://vehicle-images.carscommerce.inc/9f7a-110008194/5NMJE3AE5NH010631/2646d3179e0055fa8d903e1679001196.jpg"
  },
  {
    id: 10,
    make: "Changan",
    model: "Alsvin",
    variant: "Comfort MT",
    year: 2023,
    price: 2900000,
    city: "Lahore",
    mileage: 8000,
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Polar White",
    bodyType: "Sedan",
    engineCapacity: "1500cc",
    description: "Almost new. Minimal use. All warranty intact. Serious buyers contact only.",
    image: "https://autos.hamariweb.com/images/carimages/car_9063_993008.jpg"
  },
  {
    id: 11,
    make: "Suzuki",
    model: "Cultus",
    variant: "VXR AGS",
    year: 2021,
    price: 2600000,
    city: "Peshawar",
    mileage: 45000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Graphite Grey",
    bodyType: "Hatchback",
    engineCapacity: "1000cc",
    description: "Well maintained. No major work done. Fuel efficient city car. Original everything.",
    image: "https://suzukipakistan.com/api/media/file/mineral-grey-img-3.png"
  },
  {
    id: 12,
    make: "MG",
    model: "HS",
    variant: "Exclusive DCT",
    year: 2023,
    price: 10800000,
    city: "Karachi",
    mileage: 15000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Red Passion",
    bodyType: "SUV",
    engineCapacity: "1500cc",
    description: "Panoramic roof, digital cockpit, ADAS features. Excellent condition. Dealer maintained.",
    image: "https://www.topgear.com/sites/default/files/2023/03/MGHS-039.jpg"
  }
]

export default cars